name: xuriti
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+14

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  email_validator: ^2.1.17
  scroll_snap_list: ^0.9.1
  auto_size_text: ^3.0.0
  http: ^0.13.5
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  get_it: ^7.2.0
  percent_indicator: ^4.2.2
  flutter_svg: ^1.0.3
  card_swiper: ^2.0.4
  flutter_screenutil: ^5.6.1
  expandable: ^5.0.1
  intl:
  cloud_firestore: ^4.4.0
  path_provider: ^2.0.12
  open_file_safe_plus: ^0.0.3
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.9
  device_info_plus:
  path: ^1.8.1
  file_picker: ^5.2.6
  image_picker: 
  fluttertoast: ^8.1.3
  easy_localization:
  package_info_plus:
  webview_flutter: ^4.0.7
#  flutterfly: ^0.2.1

#  flyy_flutter_plugin: ^2.0.0

  flutter_progress_hud: ^2.0.2
  sign_in_with_apple: ^4.3.0
  font_awesome_flutter: ^10.4.0
  the_apple_sign_in: ^1.1.1
  connectivity_plus: ^2.0.2
  internet_connection_checker: ^0.0.1+4
  new_version_plus:
  sentry_flutter: ^7.5.0
  share_plus:
  flutter_keyboard_visibility: ^5.4.1
  dropdown_search: ^3.0.1
  dropdown_button2: ^2.1.0
  easy_pdf_viewer: ^1.0.6
  get:
  pinput: ^3.0.0
  cupertino_icons: ^1.0.5
  firebase_messaging: ^14.4.0
  change_app_package_name: ^1.1.0
  firebase_core: ^2.8.0
  fluttericon: ^2.0.0
  animated_svg: ^1.1.2
  flutter_local_notifications: ^10.0.0
  permission_handler: ^10.2.0
#  money_formatter: ^0.0.4
  custom_sliding_segmented_control: ^1.7.5
  flutter_flip_card: ^0.0.4
  swipe: ^0.0.1
  delayed_widget: ^1.1.2
  flame_lottie:
  flutter_secure_storage:
  blur: ^3.1.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
flutter_icons:
  image_path: "assets/images/xuriti_main_logo.jpg"
  android: true
  ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/home_images/
    - assets/images/guideImages/
    - assets/images/kycImages/
    - assets/lottie/
    - assets/lottie/greet/
    - assets/lottie/interactive_dialogs/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/PoppinsMedium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/PoppinsSemiBold.ttf
          weight: 600

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages